[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[colors.primary]
background = "#0f151a"

[font]
normal = { family = "Iosevka Nerd Font Propo", style = "Regular" }
size = 16

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[cursor]
style = { shape = "Beam", blinking = "Always" }

[window]
padding = { x = 10, y = 10 }
opacity = 0.98
