#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap us,ru -option 'grp:caps_toggle'
polybar &
picom &
gtkfix.sh
feh --bg-fill ~/Downloads/wp-3.png
setxkbmap -layout ur,ru "grp:caps_toggle"
bspc monitor -d 1 2 3 4 5
bspc config resize_hints false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
bspc config window_gap 5
bspc config bottom_padding 5
bspc config top_padding 26
bspc config border_width 2
